module ConvertedFiles.Mega.Assets.IndexDqqf6pfyJs

let file = """import{a as d,r as a,j as o}from"./index-aHpeEV8y.js";import{T}from"./ToolContent-B4ORy3df.js";import{T as f}from"./ToolTextInput-BkooUYLb.js";import{T as h}from"./ToolTextResult-CwqjGqb-.js";import{C as x}from"./CheckboxWithDesc-BstBhCI6.js";import"./TextField-3OI-XynG.js";import"./ContentPaste-DKqpSfyH.js";import"./InputFooter-BDHup-Ls.js";import"./ResultFooter-CLp_AWC-.js";import"./FormControlLabel-zEBePngt.js";import"./Checkbox-BjITWEtX.js";import"./SwitchBase-BAC9Dj1s.js";function v(t,s){return(s.caseSensitive?t:t.toLowerCase()).normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().replace(/[^\w\s-]/g,"").replace(/[\s_-]+/g,"-").replace(/^-+|-+$/g,"")}function S(t,s){return t.split(`
`).map(e=>e.trim()===""?"":v(e,s)).join(`
`)}const C={caseSensitive:!1},R=[{title:"Slug (lowercase)",description:"Convert a title into a URL-friendly slug",sampleText:"Hello World! This is a test.",sampleResult:"hello-world-this-is-a-test",sampleOptions:{caseSensitive:!1}},{title:"Slug (case preserved)",description:"Convert a title into a URL-friendly slug without any case change",sampleText:"Hello World! This is a test.",sampleResult:"Hello-World-This-is-a-test",sampleOptions:{caseSensitive:!0}},{title:"Slugs (multi lines processing)",description:"Convert titles on each lines into a URL-friendly slugs",sampleText:`Hello World! This is a test.
Multiples lines are processed`,sampleResult:`Hello-World-This-is-a-test
Multiples-lines-are-processed`,sampleOptions:{caseSensitive:!0}}];function k({title:t,longDescription:s}){const{t:e}=d("string"),[n,r]=a.useState(""),[p,u]=a.useState(""),c=(i,l)=>{u(S(l,i))},m=({values:i,updateField:l})=>[{title:e("slugGenerator.options.title"),component:[o.jsx(x,{checked:i.caseSensitive,title:e("slugGenerator.options.caseLabel"),description:e("slugGenerator.options.caseDescription"),onChange:g=>l("caseSensitive",g)},"case")]}];return o.jsx(T,{title:t,input:n,inputComponent:o.jsx(f,{value:n,onChange:r,title:e("slugGenerator.inputTitle")}),resultComponent:o.jsx(h,{value:p,title:e("slugGenerator.resultTitle")}),initialValues:C,exampleCards:R,getGroups:m,setInput:r,compute:c,toolInfo:{title:`What is a ${t}?`,description:s}})}export{k as default};
"""

let render() = file
