module ConvertedFiles.Mega.Assets.IndexJmUX04YoJs

let file = """import{a as d,r as m,j as n,B as g}from"./index-aHpeEV8y.js";import{T}from"./ToolContent-B4ORy3df.js";import{T as j}from"./ToolTextInput-BkooUYLb.js";import{T as R}from"./ToolTextResult-CwqjGqb-.js";import{T as C}from"./TextFieldWithDesc-Br8sqQWl.js";import{S as h}from"./SimpleRadio-bgT63ITl.js";import{C as b}from"./CheckboxWithDesc-BstBhCI6.js";import"./TextField-3OI-XynG.js";import"./ContentPaste-DKqpSfyH.js";import"./InputFooter-BDHup-Ls.js";import"./ResultFooter-CLp_AWC-.js";import"./Radio-43K3h4aU.js";import"./SwitchBase-BAC9Dj1s.js";import"./FormControlLabel-zEBePngt.js";import"./Checkbox-BjITWEtX.js";function u(r,t,l){const e=r.split(""),o=e.length;if(o===0)return r;const i=(t%o+o)%o;return l?e.slice(-i).concat(e.slice(0,-i)).join(""):e.slice(i).concat(e.slice(0,i)).join("")}function L(r,t,l,e){const o=[];if(e){const i=r.split(`
`);for(const p of i)o.push(u(p,t,l))}else o.push(u(r,t,l));return o.join(`
`)}const k={step:"1",direction:"right",multiLine:!0},w=[{title:"Rotate text to the right",description:"This example shows how to rotate text to the right by 2 positions.",sampleText:"abcdef",sampleResult:"efabcd",sampleOptions:{step:"2",direction:"right",multiLine:!1}},{title:"Rotate text to the left",description:"This example shows how to rotate text to the left by 2 positions.",sampleText:"abcdef",sampleResult:"cdefab",sampleOptions:{step:"2",direction:"left",multiLine:!1}},{title:"Rotate multi-line text",description:"This example shows how to rotate each line of a multi-line text.",sampleText:`abcdef
ghijkl`,sampleResult:`fabcde
lghijk`,sampleOptions:{step:"1",direction:"right",multiLine:!0}}];function H({title:r}){const{t}=d("string"),[l,e]=m.useState(""),[o,i]=m.useState(""),p=(s,a)=>{if(a){const c=parseInt(s.step,10)||1,x=s.direction==="right";i(L(a,c,x,s.multiLine))}},f=({values:s,updateField:a})=>[{title:t("rotate.rotationOptions"),component:n.jsxs(g,{children:[n.jsx(C,{value:s.step,onOwnChange:c=>a("step",c),description:t("rotate.stepDescription"),type:"number"}),n.jsx(h,{onClick:()=>a("direction","right"),checked:s.direction==="right",title:t("rotate.rotateRight")}),n.jsx(h,{onClick:()=>a("direction","left"),checked:s.direction==="left",title:t("rotate.rotateLeft")}),n.jsx(b,{checked:s.multiLine,onChange:c=>a("multiLine",c),title:t("rotate.processAsMultiLine")})]})}];return n.jsx(T,{title:r,inputComponent:n.jsx(j,{title:t("rotate.inputTitle"),value:l,onChange:e}),resultComponent:n.jsx(R,{title:t("rotate.resultTitle"),value:o}),initialValues:k,getGroups:f,toolInfo:{title:t("rotate.toolInfo.title"),description:t("rotate.toolInfo.description")},exampleCards:w,input:l,setInput:e,compute:p})}export{H as default};
"""

let render() = file
