module ConvertedFiles.DiogenesPewdiepieMd

let file = """<figure class="dio-about-hero">
  <img src="/assets/media/diogenes-of-sinope.jpg" alt="Diogenes seated with his lantern, surrounded by dogs">
</figure>

# Diogenes of Sinope

Diogenes of Sinope (l. c. 404–323 BCE) was a [Greek](https://www.worldhistory.org/disambiguation/greek/) Cynic philosopher remembered above all for the image of a man walking the streets of [Athens](https://www.worldhistory.org/Athens/) in broad daylight, holding a lantern up to the faces of passers-by and declaring that he was "searching for an honest man." He treated "manners" as nothing more than a polite lie and championed total, unflinching truthfulness in every circumstance. He was very likely a pupil of the philosopher Antisthenes (l. 445–365 BCE, himself a student of [Socrates](https://www.worldhistory.org/socrates/)) and, as [Plato](https://www.worldhistory.org/plato/) was (supposedly) quoted as saying, "a Socrates gone mad." He had been driven out of his native [city](https://www.worldhistory.org/city/) of Sinope for defacing the coinage (some accounts say it was his father who committed the offence and Diogenes merely followed him into exile). He settled in the [agora](https://www.worldhistory.org/agora/) of [Athens](https://www.worldhistory.org/Athens/), making a home for himself in a rain barrel and getting by on gifts from admirers, foraging, and begging.

That famous "search for an honest man" was Diogenes's way of laying bare the hypocrisy and theatricality of polite social convention. By holding a real light up to people's faces in full sunlight, he forced them to confront their own role in habits that kept them from living truthfully. He went on to inspire others to do the same, most notably [Crates of Thebes](https://www.worldhistory.org/Crates_of_Thebes/) (l. c. 360–280 BCE), who studied under him. Diogenes is still deeply admired today for his devotion to truth and for living exactly by his own beliefs.

The reason his figure keeps resurfacing across the ages — and it is the lens Pewdiepie brings to him in his video on Epictetus's *Discourses and Selected Writings* — is that the entire ancient Greek canon turns out to be a single, tightly braided thread. As Pewdiepie points out, Plato learned from Socrates; Aristotle studied inside Plato's school; Alexander the Great was personally taught by Aristotle; and the very Arrian who wrote down Alexander's autobiography was also Epictetus's student, recording his master's words verbatim, with Diogenes's anecdotes cropping up all the way through. "The more you dwell into it, the more you get out of it," he observes. What the Cynic and the later Stoic both share is one core conviction: that philosophy is not an abstract subject but a way of life, lived "according to nature."

## Diogenes' Beliefs

Diogenes arrived in [Athens](https://www.worldhistory.org/Athens/) and came under the wing of Antisthenes (one of many pupils of Socrates who founded his own school). Antisthenes at first turned him away but was eventually worn down by his persistence and took him on. Like his teacher, Diogenes believed in self-control, in the pursuit of personal excellence in one's conduct (the Greek *arete*, usually translated as "virtue"), and in the rejection of everything life was said to need that was in fact unnecessary — private possessions, social standing, and the rest.

He was so committed to these ideas that he lived them out in the open, on the market-place of [Athens](https://www.worldhistory.org/Athens/). He took up residence in a large wine cask (some sources say an abandoned bathtub), owned practically nothing, and appears to have survived on other people's charity. He kept a single cup that doubled as a bowl, and he threw it away after watching a boy drink straight from his cupped hands, realizing that you did not even need a cup to get by.

He also famously told [Alexander the Great](https://www.worldhistory.org/Alexander_the_Great/) to "get out of my sunlight."

Beyond this, most details grow progressively less certain, because an enormous pile of fable grew up around Diogenes and his years in Athens. Even the claim that he was Antisthenes's student has been challenged as legend. What is clear, though, is that Diogenes believed what people called "manners" were simply lies used to hide what a person really was.

He was notorious for his brutal honesty, paid no attention to etiquette of any kind across social classes, and seems to have had no problem urinating or even masturbating in public. When criticized, he pointed out that these were perfectly natural acts everyone performed; the only difference was that everyone else did them in private what he did openly.

According to Diogenes, society was a man-made contrivance that fit poorly with either truth or virtue and that could not, in any way, make someone a good or decent human being. From this follows the famous scene of him holding a light up to the faces of passers-by in the market-place, hunting for an honest man, or a real human being. Everyone, he argued, was trapped inside this make-believe world they insisted was reality, and so people were, in effect, asleep — living in a dream state.

He was not the first philosopher to make this claim. Heraclitus, Xenophanes, and above all Socrates had all argued that human beings needed to wake out of their dream state into full awareness of themselves and the world, and [Plato](https://www.worldhistory.org/plato/)'s famous *Allegory of the Cave* is devoted to exactly this theme. Diogenes, however, confronted the citizens of [Athens](https://www.worldhistory.org/Athens/) with their lifelessness and shallow values every single day, imitating his hero Socrates — whom he never actually met but would have heard of from Antisthenes. Many took him for simply mad, but Diogenes would have insisted he was living a completely honest life, and that everyone else should have the courage to do the same.

It is here, Pewdiepie notes, that the Cynic impulse and the Stoic one meet. Stoicism, whose movement takes off around the time of Aristotle's death and which draws heavily on Socrates, Plato, and Aristotle, restates the same ideal in a different register — the "main difference" being that it is "philosophy more as a way of life." Its most popularly understood principle is the division of life into what you can control and what you cannot, and the discipline of not letting the uncontrollable disturb you, of not letting it make you angry or sad. Pewdiepie renders it in plain, everyday terms: if you miss the bus, instead of getting angry you can be glad you got a good walk. And because anger and sorrow are, in Epictetus's words, "not useful emotions" — "when did anger, however, ever teach anyone to play music, or to pilot a ship?" — the goal is not to grind these feelings down but to see things for what they are and accept them. Arguing against nature, he suggests, is the tantrum of a child. The Cynic's public, unmediated "living according to nature" and the Stoic's private, reasoned acceptance of it are two faces of the same coin.

## Plato & [Alexander](https://www.worldhistory.org/disambiguation/Alexander/) the Great

This behaviour was, in part, grounded in the belief that if an act is not shameful in private, it cannot be shameful in public. The rules by which people lived were therefore nonsensical, because they forced people to behave differently from how they would naturally behave. Manners and etiquette were, in his eyes, staples of the false life inside the dream-world, and were not to be indulged.

Accordingly, he insulted his social superiors on a regular basis — Plato and Alexander the Great included. When Plato defined a human being as "a featherless biped" and was praised for the cleverness of the definition, Diogenes plucked a chicken, carried it to Plato's Academy, and announced, "Behold — Plato's human being." Plato then patched the definition with "with broad, flat nails." This was not the only occasion on which Diogenes publicly insulted Plato, but it is the best-known incident.

In the case of Alexander the Great, both Diogenes Laertius (l. c. 180–240 CE) and [Plutarch](https://www.worldhistory.org/plutarch/) (l. 45/50–120/125 CE) record that, while Diogenes was living in [Corinth](https://www.worldhistory.org/corinth/), Alexander came to the city and was very keen to meet the philosopher. He found Diogenes resting in the sunlight, introduced himself, and asked whether there was anything he could do for him. Diogenes replied, "Yes. Get out of my sunlight." Alexander, admiring his spirit, said, "If I were not Alexander, I would wish to be Diogenes," to which Diogenes answered, "If I were not Diogenes, I would also wish to be Diogenes."

On another occasion, while a group was discussing a man named Callisthenes and the fine treatment Alexander gave him, Diogenes remarked, "That man, then, is wretched, for he is forced to breakfast and dine whenever Alexander pleases." Yet another time, at a banquet for some Athenian elites, a few guests tossed Diogenes some bones and called him a dog; whereupon he lifted his leg and urinated on them. In spite of — or because of — this outrageous conduct, the Athenians adored him, and Laertius records that when a boy broke Diogenes's cask, the citizens had the boy beaten and replaced the broken one. It is unlikely, however, that Diogenes cared much for the cask or its state of repair; to him, possessions were a trap.

To be genuinely free, and to live a virtuous life of full awareness, was the ultimate meaning of a human life. As Diogenes Laertius puts it:

> On one occasion he was asked, what was the most excellent thing among men; and he said, "Freedom of speech." He was in the habit of doing everything in public, whether in respect of [Venus](https://www.worldhistory.org/venus/) or [Ceres](https://www.worldhistory.org/Ceres/); and he used to put his conclusions in this way to people: "If there is nothing absurd in dining, then it is not absurd to dine in the market-place. But it is not absurd to dine, therefore it is not absurd to dine in the market-place."

This was a reference to the ban on eating in the agora (the public market and communal space of the city), which, like every such prohibition, Diogenes simply ignored. To him, laws and rules were, like manners, artificial constructs that merely separated a person from reality and from a clear understanding of himself and the world.

Reading Epictetus, Pewdiepie draws the same line in a modern idiom, and it lands hardest on the question of what freedom actually is. Imagine a person of great wealth and power — free to go anywhere, able to control others. You could still argue that they are enslaved to that money. Money can grant freedom, but it can also bind you to it, and in that very sense make you its slave. If you lie awake at night worrying that something might happen to all the money you hold, then you do not hold your opinion "according to its nature," and you are not free from it either. Epictetus himself lived as a slave, so he must have thought about this constantly, and he knew his view was not a popular one: tell someone that they are just as enslaved as a person sold into captivity, and, in Pewdiepie's rendering of the line, "do not expect anything but a punch in the nose." What ties Diogenes's cask to Epictetus's will is one and the same truth: you can be a slave yet still be a free man, so long as your actions are free and you are not bound to anything.

## Slavery & [Death](https://www.worldhistory.org/disambiguation/Death/)

For Diogenes, a reasonable life is one lived in accordance with nature and with one's natural inclinations. To be true to oneself, then — no matter how "mad" one might appear — was to pursue a life worth living. Whether true or just another fable, the story of Diogenes's capture by pirates and sale into slavery in [Corinth](https://www.worldhistory.org/corinth/) bears witness to the strength of his convictions. When asked what talent he had, he answered, "That of governing men," and then demanded to be sold to Xeniades, saying, "Sell me to that man; for he wants a master." Even though he was a slave at this point, and in no position to demand anything, he believed so completely in himself that others felt compelled to listen and to do what he said.

Xeniades, for example, set Diogenes to tutoring his young sons, and in time the philosopher became part of the family. He lived out his life with Xeniades's household in [Corinth](https://www.worldhistory.org/corinth/) and died there at the age of ninety. His cause of [death](https://www.worldhistory.org/disambiguation/Death/) has been given variously as severe food poisoning from eating a raw ox's foot, rabies from a dog bite, or suicide by holding his breath.

The citizens of [Corinth](https://www.worldhistory.org/corinth/), like those of [Athens](https://www.worldhistory.org/Athens/), had come to admire the philosopher greatly and buried him in honour by the city gate, raising a monument over his [grave](https://www.worldhistory.org/burial/). This would have amused Diogenes, who, when asked what he wished done with his body after death, replied that it should be thrown outside the city for the dogs to feed on. A statue of him stands in modern-day Sinop, [Turkey](https://www.worldhistory.org/Asia_Minor/), showing him holding out his lantern with a dog sitting at his side.

It is exactly this "living according to nature" that, for Pewdiepie, is the most liberating idea in the whole Stoic inheritance, and the one that turns Diogenes into Epictetus's model of the free man. A Stoic's goal is, after all, to see the world for what it is and therefore to accept it — to accept age, loss, [death](https://www.worldhistory.org/disambiguation/Death/), everything from the trivial to the weather. From that acceptance follows freedom from what one owns. Epictetus holds up Diogenes as a man who was truly free, because everything he had he could dispose of and was only ever temporarily attached to it: "if you seized his leg, he would have given up the leg; if you seized his whole body, he would have sacrificed the whole body," the same being true of family, friends, and country. "He knew where these things had come from, from whom, and on what terms," so Diogenes understood that these things did not belong to him, and was therefore free from them even while still being able to enjoy them. Possessions, wealth, and even other people's opinions can all enslave a person in the same quiet way — you can be bound not just to things but to what others think of them. Yet the one thing no one, not even the gods, can take away is the will itself, which is why Epictetus calls it the supreme gift given to human beings. Diogenes, the barefoot wanderer, and Epictetus, the chain-bound slave, arrive at the same place from opposite doors: freedom is not the absence of chains, but the refusal to be bound by anything that is not truly yours.

---

*Compiled from the World History Encyclopedia article on Diogenes of Sinope (Joshua J. Mark, CC BY-NC-SA 4.0), extended and paraphrased around Pewdiepie's discussion of Epictetus's *Discourses and Selected Writings* (YouTube, "Discourses of Epictetus idk"). Worldhistory.org entity links preserved throughout.*
"""

let render() = file
