module Make.Assets.JsonToCBwDYVMryJs

let file = """import{n as e,t}from"./CommonFormats-BHch0KU5.js";let n;(function(e){class t{value;isNumericType=!0;convertValue(e){this.value=Number(e)}toCType(){return`int`}}e.IntType=t;class n{value;isNumericType=!0;convertValue(e){this.value=Number(e)}toCType(){return`float`}}e.FloatType=n;class r{value;isNumericType=!0;convertValue(e){this.value=!!e}toCType(){return`bool`}}e.BoolType=r;class i{value;isNumericType=!1;convertValue(e){this.value=e.replaceAll(`"`,``)}toCType(){return`char*`}}e.StringType=i;class a{numElements;type;value;isNumericType=!1;constructor(e,t){this.numElements=t===void 0?0:t,this.type=e,this.value=Array.from({length:this.numElements})}setNumElements(e){this.numElements=e,this.value=Array.from({length:this.numElements})}toCType(){return this.type.toCType()}convertValue(e,t){t!==void 0&&(this.type.convertValue(e),this.value[t]=this.type.value)}}e.ListType=a;class o{value;isNumericType=!1;toCType(){throw Error(`Unable to convert ObjectType to C type`)}convertValue(e){}}e.ObjectType=o;class s{value;isNumericType=!1;toCType(){return`void*`}convertValue(e){this.value=e}}e.InvalidType=s;class c{value;isNumericType=!1;toCType(){return`void*`}convertValue(e){this.value=e}}e.UndefinedType=c})(n||={});var r=class{static fromCType(e){let t=new n.InvalidType;switch(e){case`char*`:t=new n.StringType;break;case`int`:t=new n.IntType;break;case`float`:t=new n.FloatType;break;case`bool`:t=new n.BoolType;break;case`void*`:t=new n.UndefinedType;break;default:throw Error(`Invalid C type: ${e}`)}return t}static fromAny(e){let t=new n.InvalidType;if(typeof e==`string`)t=new n.StringType;else if(typeof e==`boolean`)t=new n.BoolType;else if(!isNaN(Number(e)))Number.isInteger(Number(e))?(t=new n.IntType,console.debug(`result=`),console.debug(t)):t=new n.FloatType;else if(Array.isArray(e)){if(e.length>0){if(e.every(t=>typeof t==typeof e[0])){let r=this.fromAny(e[0]);t=new n.ListType(r)}}else t=new n.ListType(new n.UndefinedType)}else typeof e==`object`&&e&&!Array.isArray(e)&&(t=new n.ObjectType);return t}},i=class{name=`jsonToC`;supportedFormats=[{name:`C Source File`,format:`c`,extension:`c`,mime:`text/x-c`,from:!0,to:!0,internal:`c`,category:t.CODE},e.JSON.supported(`json`,!0,!0)];ready=!1;offload=!0;async init(){this.ready=!0}async doConvert(e,t,n){let r=[];for(let i of e){let e=/* @__PURE__ */ new Uint8Array;switch(n.internal){case`c`:t.internal===`json`&&(console.log(`converting from .json to .c`),e=await this.jsonToC(i));break;case`json`:t.internal===`c`&&(console.log(`converting from .c to .json`),e=await this.cToJson(i))}if(e.length>0){let t=i.name.split(`.`).slice(0,-1).join(`.`)+`.`+n.extension;r.push({name:t,bytes:e})}}return r}async jsonToC(e){let t=``;t+=`#include <stdio.h>
`,t+=`#include <stdbool.h>


`;let n=`jsonObject`,r=!1,i=e.bytes,a=``;i.forEach(e=>{a+=String.fromCharCode(e)});let o={};try{o=JSON.parse(a),r=!0}catch(t){console.error(`${e.name} is not a valid JSON file: ${t}.`)}r&&(t+=await this.createStruct(n,o,0)),t+=`

int main(int argc, char** argv) {
`,t+=`
`;let s=`${n}Var`;t+=`\t${n} ${s};\n`,t+=await this.assignValues(s,o),t+=`
`,t+=`	return 0;
}`;let c=new TextEncoder;return i=new Uint8Array(c.encode(t)),i}async cToJson(e){let t=/* @__PURE__ */ new Uint8Array,i=``,a={},o={},s=[o];e.bytes.forEach(e=>{i+=String.fromCharCode(e)});let c=i.split(`
`),l=/^(?!#)[^0-9]*\.[^0-9]*/,u=/(?!(.+{$))(void\*|char\*|int|float|bool) .+/,d=/^(typedef struct|union)\s*{\s*$/,f=/^}\s*.+$/,p=/(^.+)\[(\d+)\]$/;for(let e of c){if(e=e.trim(),e=e.replaceAll(/;/g,``),e=e.replaceAll(/\s\s/g,` `),e.match(d))s.push(/* @__PURE__ */ new Map);else if(e.match(f)){let t=e.replaceAll(/}|\s/g,``);if(s.length>1){let e=s.pop(),n;if(n=s.length>1?s.pop():s[0],n!==void 0){let r=s.length-1;n[t]=e,s[r]=n,s.length===1&&(o=s[r])}}}if(e.match(u)){let t=e.split(` `),i=r.fromCType(t[0]),a=s.length-1,o=t[1],c=o.match(p);if(c!==null){let e=new n.ListType(i);o=c[1];let t=c[2];c.length==3&&e.setNumElements(Number(t)),s[a][o]=e}else s[a][o]=i}if(e.match(l)){e=e.replaceAll(/\s/g,``);let t=e.split(/\.(?!\d)/);t=t.slice(1,t.length);let r=t[t.length-1].split(`=`),i=r[0],s=r[1];t=t.slice(0,t.length-1);let c=a,l=o;for(let e of t)e in c||(c[e]={}),c=c[e],l=l[e];let u=i.match(p),d=null;if(u){if(u.length===3){i=u[1];let e=u[2];d=l[i],d instanceof n.ListType&&d.convertValue(s,Number(e))}}else d=l[i],d!==null&&d.convertValue(s);d!==null&&(c=c[i]=d.value)}}let m=JSON.stringify(a,void 0,4),h=new TextEncoder;return t=new Uint8Array(h.encode(m)),t}async createStruct(e,t,i){let a=``,o=`	`.repeat(i+1),s=`	`.repeat(i),c=!1;i>0?(a+=`	union {
`,c=!0):a+=`typedef struct {
`;for(let e in t){let s=t[e],l=r.fromAny(s);if(!(l instanceof n.InvalidType)){if(a+=o,c&&(a+=`	`),l instanceof n.ListType){let t=s.length;a+=l.type.toCType()+` `+e+`[${t}];\n`}else l instanceof n.ObjectType?a+=await this.createStruct(e,s,i+1):(l.value=s,a+=l.toCType()+` `+e+`;
`)}}return a+=s+`} `+e+`;
`,a}async assignValues(e,t){let i=``;for(let a in t){let o=t[a],s=r.fromAny(o);if(!(s instanceof n.InvalidType)){if(s instanceof n.ListType){let t=0;for(let n in o)i+=`\t${e}.${a}[${t}] = ${n};\n`,t++}else s instanceof n.ObjectType?i+=await this.assignValues(`${e}.${a}`,o):s instanceof n.StringType?i+=`\t${e}.${a} = "${o}";\n`:s instanceof n.UndefinedType?i+=`\t${e}.${a} = (void*) (${o});\n`:s.isNumericType&&(i+=`\t${e}.${a} = ${o};\n`)}}return i}};export{i as default};"""

let render() = file
