source "https://rubygems.org"

gem "jekyll", "~> 4.3"

# Minima theme - using the specific commit that vllm uses
gem "minima", github: "jekyll/minima", ref: "5ce4006d175e6e5278bb63a0aad1a85e3bf2370b"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-gfm-admonitions"
  gem "jekyll-redirect-from"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1", :platforms => [:mingw, :x64_mingw, :mswin]
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
